taqatools/members/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    # deal with members register/read/update/delete - login/logout
    path('register/', views.register_user, name = 'register'),
    path('login/', views.login_user, name = 'login'),
    path('logout/', views.logout_user, name = 'logout'),
    path('members/<slug:username>/', views.user_profile, name = 'user_profile'),
    path('members/<slug:username>/delete/', views.user_delete, name = 'user_delete'),
    path('members/<slug:username>/picture/', views.update_picture, name = 'update_picture'),
    path('members/', views.users, name = 'members'),
    # deal with companies add/read/update/delete
    path('company/add/', views.add_company, name = 'add_company'),
    path('company/update/<slug:slug>/', views.update_company, name = 'update_company'),
    path('company/delete/<slug:slug>/', views.delete_company, name = 'delete_company'),
    path('company/<slug:slug>/', views.co_profile, name = 'co_profile'),
    path('companies/', views.co_list, name = 'companies'),
    # deal with company categories add/read/update/delete
    path('company/category/add/', views.add_co_category, name = 'add_co_category'),
    path('company/category/update/<slug:slug>', views.update_co_category, name = 'update_co_category'),
    path('company/category/delete/<slug:slug>', views.delete_co_category, name = 'delete_co_category'),
    path('company/category/all/', views.co_category_list, name = 'co_category_list'),
    path('company/category/<slug:slug>/', views.co_category_profile, name='co_category_profile'),
    # Address
    path('address/add/gov/', views.add_gov, name='add_gov'),
    path('address/add/city/', views.add_city, name='add_city'),
    path('address/add/address/', views.add_address, name='add_address'),
    
    
    
    path('paymob/', views.paymob, name='paymob'),
    path('paymob/status/', views.payment_status, name='payment_status'),
    
    
    path('not-authinticated/', views.not_auth, name='not_auth'),
    path('company-only/', views.company_only, name='company_only'),
    path('users-only/', views.users_only, name='users_only')
    
]

taqatools/posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('posts/', views.posts, name='posts'),
    path('posts/add-post/', views.add_post, name='add_post'),
    path('post/<slug:slug>/', views.post_view, name='post'),
    path('post/category/<slug:slug>/', views.post_category, name='post_category'),
    path('post/<slug:slug>/edit/', views.post_edit, name='post_edit'),
    path('post/<slug:slug>/delete/', views.post_delete, name='post_delete'),
]

taqatools/taqatools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('django.contrib.auth.urls')),
    path('', include('members.urls')),
    path('', include('products.urls')),
    path('', include('accounting.urls')),
    path('', include('posts.urls')),
    path('', include('sitestats.urls')),
    path('', include('pumpoffers.urls')),
    path('', include('tenders.urls')),
    path('', include('payments.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taqatools/members/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.utils.text import slugify
from sitestats.models import Site
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_resized import ResizedImageField



def arabic_to_english_slug(text):
    # Define a dictionary that maps Arabic characters to their corresponding English characters
    arabic_to_english_map = {
        'ا': 'a',
        'أ': 'a',
        'إ': 'e',
        'ب': 'b',
        'ت': 't',
        'ث': 'th',
        'ج': 'j',
        'ح': 'h',
        'خ': 'kh',
        'د': 'd',
        'ذ': 'th',
        'ر': 'r',
        'ز': 'z',
        'س': 's',
        'ش': 'sh',
        'ص': 's',
        'ض': 'dh',
        'ط': 't',
        'ظ': 'dth',
        'ع': '3',
        'غ': 'gh',
        'ف': 'f',
        'ق': 'q',
        'ك': 'k',
        'ل': 'l',
        'م': 'm',
        'ن': 'n',
        'ه': 'h',
        'و': 'w',
        'ي': 'y',
        'ئ': 'e',
        'ء': 'a',
        'ؤ': 'o',
        'ة': 'h',
        'ى': 'a',
        # Add more mappings here
    }
    # Create a new string that replaces the Arabic characters with their corresponding English characters
    english_text = ''.join([arabic_to_english_map.get(char, char) for char in text])
    # Use the Django slugify function to generate the slug from the English text
    slug = slugify(english_text)
    return slug




class Gov(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
    
class City(models.Model):
    name = models.CharField(max_length=100)
    gov = models.ForeignKey(Gov, on_delete=models.CASCADE, related_name='cities')

    def __str__(self):
        return self.name
    
class Address(models.Model):
    details = models.CharField(max_length=200)
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='addresses')

    def __str__(self):
        return self.details
    
    @property
    def location(self):
        return f'{self.city.gov.name}، {self.city.name}، {self.details}'



class CoCategory(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    slug = models.SlugField(max_length=150, blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        if not self.slug:
            self.slug = arabic_to_english_slug(self.name)
        super(CoCategory, self).save(*args, **kwargs)

class Company(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(max_length=500)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    website = models.URLField(max_length=200, null = True)
    address = models.ForeignKey(Address, on_delete = models.CASCADE, related_name = 'company')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='company')
    category = models.ManyToManyField(CoCategory, related_name='companies', null= True)
    slug = models.SlugField(max_length=150, blank=True)
    count = models.ForeignKey(Site, on_delete=models.SET_DEFAULT, default=1)
    image = ResizedImageField(size=[300, 300], upload_to='images', null= True, blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        if not self.slug:
            self.slug = arabic_to_english_slug(self.name)
        super(Company, self).save(*args, **kwargs)
        self.count.companies += 1
        self.count.save()

def balance(self):
    sales = sum(invoice.total_value for invoice in self.sale.all())
    purchases = sum(invoice.total_value for invoice in self.purchase.all())
    payments = sum(payment.value for payment in self.credit.all())
    receipts = sum(receipt.value for receipt in self.depit.all())
    return -sales+purchases-payments+receipts

User.add_to_class('balance', balance)

def full_name(self):
    return f'{self.first_name} {self.last_name}'

User.add_to_class('full_name', full_name)

@receiver(post_save, sender=User)
def user_account_details(sender, instance, created, **kwargs):
    if created:
        details = Details.objects.create()
        Account.objects.create(user=instance, details= details)
        if not Site.objects.get(id=1):
            Site.objects.create()
        users_no =Site.objects.get(id=1)
        users_no.users   += 1
        users_no.save()
        
def has_company(self):
    return self.company.count()

User.add_to_class('has_company', has_company)



class Details(models.Model):
    sales_no = models.PositiveSmallIntegerField(default=0)
    sales_value = models.FloatField(default=0)
    purchases_no = models.PositiveSmallIntegerField(default=0)
    purchases_value = models.FloatField(default=0)
    offers_no = models.PositiveSmallIntegerField(default=0)
    offers_value = models.FloatField(default=0)
    payments_no = models.PositiveSmallIntegerField(default=0)
    payments_value = models.FloatField(default=0)
    receipts_no = models.PositiveSmallIntegerField(default=0)
    receipts_value = models.FloatField(default=0)
    
        

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    details = models.OneToOneField(Details, on_delete=models.CASCADE)
    image = ResizedImageField(size=[300, 300], upload_to='images', null= True, blank=True)
    @property
    def member(self):
        return self.user
    
    

taqatools/members/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Company, CoCategory, Details, Account, Gov, City, Address

class RegisterUserForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})
        self.fields['username'].label = 'رقم التليفون'
        self.fields['username'].help_text = 'ادخل رقم الواتس اب الخاص بك'
        self.fields['first_name'].label = 'الاسم الاول'
        self.fields['last_name'].label = 'الاسم الاخير'
        self.fields['email'].label = 'البريد الاليكتروني'
        self.fields['password1'].label = 'رمز الدخول السري'
        self.fields['password2'].label = 'تأكيد رمز الدخول السري'
        self.fields['password2'].help_text = 'ادخل نفس الرمز الذي ادخلته من قبل للتأكيد'


class AddCompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = ('name', 'description', 'image', 'phone', 'email', 'website', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['image'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['website'].widget.attrs.update({'class': 'form-control'})
        
        self.fields['name'].label = 'اسم الشركة'
        self.fields['description'].label = 'نبذة عن الشركة'
        self.fields['image'].label = 'لوجو الشركة'
        self.fields['phone'].label = 'رقم التليفون'
        self.fields['email'].label = 'البريد الاليكتروني'
        self.fields['website'].label = 'موقع الويب'






class AddCoCategoryForm(forms.ModelForm):

    class Meta:
        model = CoCategory
        fields = ('name', 'description')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['name'].label = 'اسم التخصص'
        self.fields['description'].label = 'نبذة عن التخصص'
  
  
        
class DetailsForm(forms.ModelForm):

    class Meta:
        model = Details
        fields = "__all__"


        
class AccountForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = "__all__"






class AddGovForm(forms.ModelForm):

    class Meta:
        model = Gov
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['name'].label = 'اسم المحافظة'






class AddCityForm(forms.ModelForm):

    class Meta:
        model = City
        fields = ('name', 'gov')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['gov'].widget.attrs.update({'class': 'form-control'})
        self.fields['name'].label = 'اسم المدينة'
        self.fields['gov'].label = 'المحافظة التابعة لها'




class AddAddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = ('details',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['details'].widget.attrs.update({'class': 'form-control'})
        self.fields['details'].label = 'العنوان بالتفصيل'
  

taqatools/templates/members/company/add_company.html
{% extends 'base.html' %}
{% load static %}
{% block title %} اضف شركة  {% endblock %}
{% block content %}




<div class="container my-1 mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">اضافة شركة</h4>
        </div>
        <div class="card-body">
          <form action="{% url 'add_company' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>
            {{ form.as_p }}
              <label for="id_gov">المحافظة:</label>
              <select name="gov" class="form-control" required="" id="id_gov">
                <option value="" selected="">---------</option>
                {% for gov in govs %}
                <option value="{{gov.id}}">{{ gov.name }}</option>
                {% endfor %}
              </select>
            </p>
            
            <p>
              <label for="id_city">المدينة او المركز:</label>
              <select name="city" class="form-control" required="" id="id_city">
                <option value="" selected="">---------</option>
              </select>
            </p>
            {{ address_form.as_p }}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
            <div class="d-grid mb-3">
              <button type="submit" class="btn btn-primary">إضافة</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'pumpoffers/gov_select.js' %}"></script>
  <!-- <script src="{% static '/membersjs/add_company.js' %}"></script> -->
{% endblock %}

taqatools/templates/members/company/co_list.html
{% extends 'base.html' %}
{% load static %}
<!-- comment  -->
{% block title %}قائمة الشركات  {% endblock %}
<!-- comment  -->
{% block content %}

<!-- <link rel="stylesheet" href="{% static 'membersjs/co_list.css' %}"> -->

<div class="container py-3  px-4 px-lg-5 my-2">
    <div class="row gx-4 gx-lg-5 align-items-center">
        <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="/images/favicon.ico" alt="..." height="250" /></div>
        <div class="col-md-6">
            <div class="small mb-1">قسم الشركات</div>
            <h1 class="display-5 fw-bolder">الشركات المشتركة في الموقع</h1>
            <div class="fs-5 mb-5">
                <span>عدد الشركات المشتركة {{ companies.count }} شركة</span>
            </div>
        </div>
    </div>
</div>
    <!-- Related items section-->
        <div class="container px-4 px-lg-5 mt-2">
            <h2 class="fw-bolder mb-4">قائمة الشركات</h2>
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for company in companies %}
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        {% if company.image %}
                        <img class="card-img-top" src="{{company.image.url}}" alt="..." height="125"/>
                        {% endif %}
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{company.name}}</h5>
                                <!-- Product price-->
                                {{company.description}}
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'co_profile' company.slug %}">المزيد عن الشركة</a></div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock %} 

taqatools/templates/members/company/co_profile.html
{% extends 'base.html' %}
{% load static %}
<!-- comment -->
{% block title %} {{company.name}} {% endblock %}
<!-- comment -->
{% block content %}

<div class="container py-3  px-4 px-lg-5 my-2">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#update-company-modal">
        تعديل
    </button>

    <div class="modal fade" id="update-company-modal" tabindex="-1" aria-labelledby="update-company-modal"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="update-company-modal">تعديل</h5>
                    <button type="button" class="btn-close me-auto ms-0" data-bs-dismiss="modal"
                        aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form enctype="multipart/form-data" action="{% url 'update_company' company.slug %}" method="post"
                        name="update-company_form">
                        {% csrf_token %} 
                        <p>
                        {{ form.as_p }}
                          <label for="id_gov">المحافظة:</label>
                          <select name="gov" class="form-control" required="" id="id_gov">
                            <option value="{{company.address.city.gov.id}}" selected="">{{ company.address.city.gov.name }}</option>
                            {% for gov in govs %}
                            {% if not gov.id == company.address.city.gov.id %}
                            <option value="{{gov.id}}">{{ gov.name }}</option>
                            {% endif %}
                            {% endfor %}
                          </select>
                        </p>
                        
                        <p>
                          <label for="id_city">المدينة او المركز:</label>
                          <select name="city" class="form-control" required="" id="id_city">
                            <option value="{{company.address.city.id}}" selected="">{{company.address.city.name}}</option>
                          </select>
                        </p>
                        {{ address_form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            تعديل
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete-company-modal">
        حذف
    </button>
    <br /><br />

    <!-- delete-company-modal.html -->

    <div class="modal fade" id="delete-company-modal" tabindex="-1" aria-labelledby="delete-company-modal-label"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="delete-company-modal-label">
                        حذف الشركة
                    </h5>
                    <button type="button" class="btn-close me-auto ms-0" data-bs-dismiss="modal"
                        aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    هل انت متأكد من حذف هذه الشركة؟
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                        إالغاء
                    </button>
                    <form action="{% url 'delete_company' company.slug %}" method="POST">
                        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
                        <button type="submit" class="btn btn-danger" id="confirm-delete-company">
                            تأكيد الحذف
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row gx-4 gx-lg-5 align-items-center">
        <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{company.image.url}}" alt="..." /></div>
        <div class="col-md-6">
            <div class="small mb-1"></div>
            <h1 class="display-5 fw-bolder">{{ company.name }}</h1>
            <div class="fs-5 mb-5">
                <span>{{ company.description }}</span>
            </div>
            <p>{{company.owner.full_name}}</p>
            <p><i class='bx bx-phone'></i> {{company.phone}}</p>
            <p>@ {{company.email}}</p>
            <p>{{company.website}}</p>
            <p><i class='bx bx-map'></i> {{company.address.location}}</p>
        </div>
    </div>
</div>
<!-- Related items section-->
<div class="container px-4 px-lg-5 mt-2">
    {% if company.tender_offers.count %}
    <h5 class="fw-bolder mb-4">عروض الاسعار المقدمة من الشركة</h5>
    {% else %}
    <h5 class="fw-bolder mb-4">لا توجد عروض اسعار مقدمة من شركة {{ company.name }} حتى الان</h5>
    {% endif %}
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for offer in company.tender_offers.all %}
        <div class="col mb-5">
            <div class="card h-100">
                <!-- Sale badge-->
                <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                <!-- Product image-->
                <img class="card-img-top" src="{{offer.company.image.url}}" height="150" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{offer.request.tender.name}}</h5>
                        <!-- Product price-->
                        {{offer.value}}
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                            href="{% url 'offer_profile' offer.id %}">تفاصيل العرض</a></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script src="{% static 'pumpoffers/gov_select.js' %}"></script>
{% endblock %}

taqatools/templates/members/company/update_company.html
{% extends 'base.html' %}
{% block title %} تعديل شركة  {% endblock %}
{% block content %}

<div class="shadow p-3 mb-5 bg-white rounded">
  <h3>
    تعديل شركة {{ company.name }}  
  </h3>
  <br>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">تعديل</button>
  </form>
</div>
{% endblock %}